### ISSUE TITLE
一直Refresh Node

### ISSUE THREAD

**Issue by 22h33j** [MoeClub/vList#3]
按照教程编写配置文件，并在win运行，一直提示Refresh Node···
![微信图片_20220126154451](https://user-images.githubusercontent.com/70189449/151123024-071c2242-a55d-4566-b0e8-637a6eab2f78.png)
希望大佬有时间回复下..谢谢大佬

**Comment by MoeClub** [comment]
这是正常的，打印这个输出的时候，就可以直接访问了。
无须等待，缓存了多少直接显示多少。
